### ISSUE TITLE
Works very unstable. 

### ISSUE THREAD

**Issue by Ispolin08** [merorafael/telegram-handler#4]
Hello. 
Tried it on 2 different php versions and servers. If i try to send 2messages using this handler with some sleep between - it works in 10% cases. If I use file_get_conetnts(api.telegram blalblabla) - works perfect. If i combine it in each case I will get only one message (from http request from file_get_conetnts). 

So I get inside streamHandler in monolog. 
If i add 
/**
     * Wrapper to allow mocking
     */
    protected function fwrite($data)
    {
        $a  = fwrite($this->resource, $data);
echo fgets($this->resource); <-----------------
return $a;
    }

I see HTTP 200 and it works FINE. When remove - same problem again. 

I am planning to send messages using another handler.

**Comment by merorafael** [comment]
Hello,

Do you can send me a pull request with this change? I will test this change before approve.

The actualy method uses the same feature that HipChat and Slack handlers, I not understand why the telegram API has this issue with this feature.

**Comment by merorafael** [comment]
Please, specify also the PHP version and OS where you find this issue.

**Comment by daartkote** [comment]
Same problem. I use mattermost and telegram. I send 25 messages, mattermost received 25 messages telegram only 6

**Comment by merorafael** [comment]
Hello guys,

The 0.3.0 version is released, this version change socket communication to use cURL extension and HtmlFormatter for Telegram API is added. Do you can confirm if this release has more stability?
