### ISSUE TITLE
Depending symfony/yaml

### ISSUE THREAD

**Issue by arnidan** [merorafael/telegram-handler#5]
Hi, you are using `symfony/yaml` package for `HtmlFormatter`. Can you please add it as composer requirement?

**Comment by dmitryuk** [comment]
https://github.com/merorafael/telegram-handler/pull/6

**Comment by merorafael** [comment]
Resolved in this commit: https://github.com/merorafael/telegram-handler/commit/5e8efad305724559bf93b76440e05c2d116a3187
